### PR TITLE
Admin merch top5

### PR DESCRIPTION
**Pull request by Shawnl93**

### CODE REVIEW

**Comment by Shawnl93** [comment]
that was a hefty US

**Review by naomiyocum — APPROVED** [review]
Nice!!

**Comment by Shawnl93** [comment]
Added "invoice_item" 9-12 
Added Merchants, shawn kristen yuji

**Review by Yuji3000 — APPROVED** [review]
nice work. All tests pass! I added an "s" to the top_five_merchant method before merging.

**Pull request merged**
